FROM ubuntu:18.04

ENV USER=ipfsuser06
ENV UID=12345
ENV GID=23456

RUN groupadd -g "$GID" ipfsuser 
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/home/ipfsuser06" \
    --uid "$UID" \
    --ingroup ipfsuser \
    "$USER"

RUN apt-get update -y && apt-get upgrade -y 
RUN apt-get install -y build-essential

USER ipfsuser06
RUN mkdir /home/ipfsuser06/ipfsHome
WORKDIR /home/ipfsuser06/ipfsHome

# Bring in and extract directly (that's what 'ADD' can do) 
ADD go-ipfs_v0.4.22_linux-amd64.tar.gz .
# Going to install IPFS command now..
# I needed root and I did not want to perform previous steps again so I am going to switch between users using "USER" instruction
USER root
# Switching to root because "install.sh" requires root permissions and I'm not going to put "sudo" package above in list of packages due to the previously told reason (don't want rebuilding and eventually 'npm install').
RUN cd go-ipfs && chmod +x ./install.sh && \
    ./install.sh

# Switched back
USER ipfsuser06

RUN  ipfs init
# Changing IPs to 0.0.0.0 so that it supports all requests.. (potentially insecure)
RUN ipfs config Addresses.API /ip4/0.0.0.0/tcp/5001     \
    && ipfs config Datastore.GCPeriod 30m \
    && ipfs config Addresses.Gateway /ip4/0.0.0.0/tcp/8080     \
    && ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '[         "http://localhost:3000", "http://127.0.0.1:3000", "http://0.0.0.0:3000", "http://127.0.0.1:8080", "http://0.0.0.0:8080",         "http://127.0.0.1:9095", "http://0.0.0.0:9095", "http://127.0.0.1:9094", "http://0.0.0.0:9094", "http://0.0.0.0:9096",         "http://127.0.0.1:5001", "http://0.0.0.0:5001", "http://localhost:5001", "http://localhost:5002",  "http://0.0.0.0:5002",         "http://127.0.0.1:5002", "*"     ]'     \
    && ipfs config --json Gateway.HTTPHeaders.Access-Control-Allow-Origin '[         "http://localhost:3000", "http://127.0.0.1:3000", "http://0.0.0.0:3000", "http://127.0.0.1:8080", "http://0.0.0.0:8080",         "http://127.0.0.1:9095", "http://0.0.0.0:9095", "http://127.0.0.1:9094", "http://0.0.0.0:9094", "http://0.0.0.0:9096",         "http://127.0.0.1:5001", "http://0.0.0.0:5001", "http://localhost:5001", "http://localhost:5002",  "http://0.0.0.0:5002",         "http://127.0.0.1:5002", "*"     ]'     \
    && ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '[ "GET", "PUT", "POST"  ]'     \
    && ipfs config --json Gateway.HTTPHeaders.Access-Control-Allow-Methods '[ "GET", "PUT", "POST"  ]'     \
    && ipfs config --json API.HTTPHeaders.Access-Control-Allow-Headers '[ "X-Requested-With","Range","User-Agent"]'     \
    && ipfs config --json Gateway.HTTPHeaders.Access-Control-Allow-Headers '[ "X-Requested-With","Range","User-Agent"]'
EXPOSE 5001

# Need root user for installing Tini
USER root
# Add Tini
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "-s", "--"]

# Switching back to normal user
USER ipfsuser06
# Run your program under Tini
CMD ["ipfs", "daemon", "--enable-gc"]

